// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem.Data;

#nullable disable

namespace SchoolManagementSystem.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260108152525_AddStudentAttendance")]
    partial class AddStudentAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.BusTable", b =>
                {
                    b.Property<int>("BusNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusNo"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BusSupervisor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PlateNo")
                        .HasColumnType("int")
                        .HasColumnName("plateNo");

                    b.Property<int?>("SupervisorMobile")
                        .HasColumnType("int");

                    b.HasKey("BusNo");

                    b.ToTable("BusTable");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Committee", b =>
                {
                    b.Property<int>("ComNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comNo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComNo"));

                    b.Property<string>("ComLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("comLocation");

                    b.Property<string>("ComSection")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Grade")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Mahroom")
                        .HasColumnType("int");

                    b.Property<int?>("SpNeeds")
                        .HasColumnType("int");

                    b.Property<int?>("StdCount")
                        .HasColumnType("int");

                    b.Property<string>("Transport")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("transport");

                    b.HasKey("ComNo");

                    b.ToTable("committee");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<DateTime?>("CourseDateN")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("courseDateN");

                    b.Property<string>("CourseName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.CousreDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CousreId")
                        .HasColumnType("int")
                        .HasColumnName("cousreID");

                    b.Property<long?>("StdId")
                        .HasColumnType("bigint")
                        .HasColumnName("StdID");

                    b.HasKey("Id");

                    b.HasIndex("CousreId");

                    b.HasIndex(new[] { "StdId" }, "CousreDate$StdID");

                    b.ToTable("CousreDate");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamAb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<bool?>("Present")
                        .HasColumnType("bit");

                    b.Property<byte[]>("SsmaTimeStamp")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<long?>("StdId")
                        .HasColumnType("bigint")
                        .HasColumnName("StdID");

                    b.Property<string>("Stdstatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CourseId" }, "ExamAbs$CourseID");

                    b.HasIndex(new[] { "StdId" }, "ExamAbs$StdID");

                    b.ToTable("ExamAbs");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamStd", b =>
                {
                    b.Property<long>("StdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("StdID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StdId"));

                    b.Property<int?>("G")
                        .HasColumnType("int")
                        .HasColumnName("G#");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StdComNo")
                        .HasColumnType("int");

                    b.Property<string>("StdGrade")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StdMobile")
                        .HasColumnType("int");

                    b.Property<string>("StdName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StdSeat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StdTransport")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StdId");

                    b.ToTable("ExamStd");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.GradeTable", b =>
                {
                    b.Property<string>("GradeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GradeID");

                    b.Property<string>("GradeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GradeId");

                    b.ToTable("GradeTable");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.LateTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LateDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("LateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Qid")
                        .HasColumnType("bigint")
                        .HasColumnName("QID");

                    b.Property<int?>("Sms")
                        .HasColumnType("int")
                        .HasColumnName("SMS");

                    b.Property<string>("StdGrade")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StdMobile")
                        .HasColumnType("int");

                    b.Property<string>("StdName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "LateTable$ID");

                    b.ToTable("LateTable");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GradeID");

                    b.Property<long?>("TeachId")
                        .HasColumnType("bigint")
                        .HasColumnName("TeachID");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex(new[] { "Id" }, "Relation$ID");

                    b.HasIndex(new[] { "TeachId" }, "Relation$TeachID");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StdTable", b =>
                {
                    b.Property<long>("Qid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("QID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Qid"));

                    b.Property<int?>("BusNo")
                        .HasColumnType("int");

                    b.Property<string>("GradeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GradeID");

                    b.Property<double?>("Mobile2")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OldBranche")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OldSchool")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Sms")
                        .HasColumnType("int")
                        .HasColumnName("SMS");

                    b.Property<byte[]>("SsmaTimeStamp")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<int>("StdCode")
                        .HasColumnType("int");

                    b.Property<int?>("StdComNo")
                        .HasColumnType("int");

                    b.Property<int?>("StdMobile")
                        .HasColumnType("int");

                    b.Property<string>("StdName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StdNationality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StdSeat")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Qid");

                    b.HasIndex("BusNo");

                    b.HasIndex("GradeId");

                    b.HasIndex("StdComNo");

                    b.HasIndex(new[] { "StdCode" }, "StdTable$StdCode")
                        .IsUnique();

                    b.ToTable("StdTable");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StudentAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "ClassId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("StudentAttendance");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.TeacherTb", b =>
                {
                    b.Property<long>("TeachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TeachID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeachId"));

                    b.Property<int?>("CousreId")
                        .HasColumnType("int")
                        .HasColumnName("CousreID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<int?>("TeachMobile")
                        .HasColumnType("int");

                    b.Property<string>("TeachName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeachId");

                    b.HasIndex(new[] { "CousreId" }, "TeacherTb$CousreID");

                    b.HasIndex(new[] { "StaffId" }, "TeacherTb$StaffID");

                    b.ToTable("TeacherTb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.CousreDate", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Course", "Cousre")
                        .WithMany("CousreDates")
                        .HasForeignKey("CousreId");

                    b.HasOne("SchoolManagementSystem.Models.StdTable", "Std")
                        .WithMany("CousreDates")
                        .HasForeignKey("StdId");

                    b.Navigation("Cousre");

                    b.Navigation("Std");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamAb", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Course", "Course")
                        .WithMany("ExamAbs")
                        .HasForeignKey("CourseId");

                    b.HasOne("SchoolManagementSystem.Models.StdTable", "Std")
                        .WithMany("ExamAbs")
                        .HasForeignKey("StdId");

                    b.Navigation("Course");

                    b.Navigation("Std");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Relation", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.GradeTable", "GradeNavigation")
                        .WithMany("Relations")
                        .HasForeignKey("GradeId");

                    b.HasOne("SchoolManagementSystem.Models.TeacherTb", "Teach")
                        .WithMany("Relations")
                        .HasForeignKey("TeachId");

                    b.Navigation("GradeNavigation");

                    b.Navigation("Teach");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StdTable", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.BusTable", "BusNoNavigation")
                        .WithMany("StdTables")
                        .HasForeignKey("BusNo");

                    b.HasOne("SchoolManagementSystem.Models.GradeTable", "StdGradeNavigation")
                        .WithMany("StdTables")
                        .HasForeignKey("GradeId");

                    b.HasOne("SchoolManagementSystem.Models.Committee", "StdComNoNavigation")
                        .WithMany("StdTables")
                        .HasForeignKey("StdComNo");

                    b.Navigation("BusNoNavigation");

                    b.Navigation("StdComNoNavigation");

                    b.Navigation("StdGradeNavigation");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StudentAttendance", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.GradeTable", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.StdTable", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Models.TeacherTb", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.TeacherTb", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Course", "Cousre")
                        .WithMany("TeacherTbs")
                        .HasForeignKey("CousreId");

                    b.Navigation("Cousre");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.BusTable", b =>
                {
                    b.Navigation("StdTables");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Committee", b =>
                {
                    b.Navigation("StdTables");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Course", b =>
                {
                    b.Navigation("CousreDates");

                    b.Navigation("ExamAbs");

                    b.Navigation("TeacherTbs");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.GradeTable", b =>
                {
                    b.Navigation("Relations");

                    b.Navigation("StdTables");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StdTable", b =>
                {
                    b.Navigation("CousreDates");

                    b.Navigation("ExamAbs");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.TeacherTb", b =>
                {
                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
